# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

language: "en-US"

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  path_filters:
    - "!**/*.lock"
    - "!**/node_modules/**"
    - "!**/__pycache__/**"
    - "!**/*.pyc"
    - "!**/dist/**"
    - "!**/coverage/**"
    - "!**/*.egg-info/**"
    - "!**/venv/**"
    - "!**/.venv/**"

  path_instructions:
    - path: "**/*.py"
      instructions: |
        Focus on Python best practices:
        - Type hints usage
        - Error handling patterns
        - Async/await patterns for voice processing
        - API integration safety

    - path: "**/voice/**/*.py"
      instructions: |
        Review voice processing code for:
        - Audio handling safety
        - Speech recognition accuracy
        - Text-to-speech integration
        - Error recovery

    - path: "**/assistant/**/*.py"
      instructions: |
        Review assistant logic for:
        - Command parsing accuracy
        - Response generation
        - State management

    - path: "**/*test*.py"
      instructions: |
        Ensure tests are:
        - Testing behavior, not implementation
        - Using proper assertions
        - Covering edge cases
        - Mocking external APIs properly

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

chat:
  auto_reply: true
